[WIP] [#25] [API] As a user, I can sign up
markgravity/golang-ic pull request #40
Opened 2023-08-21 10:10 UTC by markgravity

- Close #25 

## What happened 👀

Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.

## Insight 📝

Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.

## Proof Of Work 📹

Show us the implementation: screenshots, GIFs, etc.

2023-08-22 03:57 UTC, suho requested changes

2023-08-22 03:57 UTC, suho commented on lib/api/v1/controllers/auth.go
> +	"github.com/gin-gonic/gin"
```suggestion
	"net/http"
	
	errorhelpers "github.com/markgravity/golang-ic/helpers/error"
	jsonhelpers "github.com/markgravity/golang-ic/helpers/json"
	"github.com/markgravity/golang-ic/lib/api/v1/forms"

	"github.com/gin-gonic/gin"
```

2023-08-22 03:57 UTC, suho commented on lib/api/v1/routers/router.go
> -	})
Why you removed this

2023-08-22 03:57 UTC, suho commented on lib/api/v1/controllers/auth_test.go
> +	Describe("POST /sign-in", func() {
You are implementing sign-up but test sign-in

```suggestion
	Describe("POST /sign-in", func() {
```

2023-08-22 06:34 UTC, markgravity commented on lib/api/v1/routers/router.go
> -	})
Revert it 🙏

2023-08-22 06:34 UTC, markgravity commented
@suho resolved your comments [e987a5e](https://github.com/markgravity/golang-ic/pull/40/commits/e987a5e34b4689089218e8721f900d4b41400e82)

2023-08-22 07:48 UTC, malparty commented on helpers/error/error.go
> +func IsTimeout(err error) bool {
```suggestion
func isNotFound(err error) bool {
	if err == nil {
		return false
	}

	return strings.Contains(strings.ToUpper(err.Error()), NotFound)
}

func isTimeout(err error) bool {
```

These can be made private 🤔

2023-08-22 08:29 UTC, malparty requested changes
Just early comments I will continue tomorrow as I'm running out of time for today 🙇

2023-08-22 08:29 UTC, malparty commented on lib/api/v1/forms/sign_up_test.go
> +				test.CleanUpDatabase()
What about using a callback for this generic "chore"?

```go
	AfterEach(func() {
		test.CleanUpDatabase()
	})
```

(to be placed as the first instruction inside the root "Describle" block :)

2023-08-22 08:29 UTC, malparty commented on lib/api/v1/controllers/auth.go
> +		jsonhelpers.RenderErrorWithDefaultCode(ctx, statusCode, err)
I see there is already a list of error codes in the JSON helper. 
Wouldn't is be more explicit and straight forward if we had a method like:

```suggestion
		jsonhelpers.RenderUnprocessableEntityError(ctx, err)
```

According to the controller tests, there is only this error possible (or at least, tested ^^).

2023-08-23 02:46 UTC, markgravity commented
@malparty resolved at [b70c3da](https://github.com/markgravity/golang-ic/pull/40/commits/b70c3daee648a1949dccf370e357429773e72883) 🙏

2023-08-23 06:57 UTC, suho approved these changes

2023-08-23 08:28 UTC, malparty commented on helpers/error/error.go
Sorry for that, but with the last change, this file is not used anymore 🙈

2023-08-23 08:34 UTC, markgravity commented on helpers/error/error.go
@malparty removed them 🙏

2023-08-23 09:06 UTC, malparty requested changes
I made it through the PR!
Please check carefully all the added functions to ensure they are all needed, and that they have the expected exposure (public/private).

It's always preferable to use a non-exposed function because:
- no need to write tests for it
- future coding will be more consistent as less options to chose on the interfaces available
- moving from private to public is safer and easier that moving from public to private

2023-08-23 09:06 UTC, malparty commented on helpers/json/response_json.go
> +func RenderError(ctx *gin.Context, statusCode int, errMessage string, errorCode string) {
```suggestion
func renderError(ctx *gin.Context, statusCode int, errMessage string, errorCode string) {
```

It seems that at the moment you don't need to expose this function

2023-08-23 09:06 UTC, malparty commented on helpers/json/response_json.go
> +func RenderErrorWithMeta(ctx *gin.Context, statusCode int, errMessage string, errorCode string, meta *map[string]interface{}) {
This function is not used anywhere too.

2023-08-23 09:06 UTC, malparty commented on helpers/json/response_json.go
> +func RenderJSONWithMeta(ctx *gin.Context, code int, data interface{}, meta *jsonapi.Meta) {
```suggestion
func renderJSONWithMeta(ctx *gin.Context, code int, data interface{}, meta *jsonapi.Meta) {
```

2023-08-23 09:06 UTC, malparty commented on lib/validators/translations.go
> +	},
Should we move this into YML files? (see https://github.com/nimblehq/varun-api/blob/develop/locales/en.yaml ).

As translations must be easily pulled from external systems/API (like Phrase).

This can be done is a new story (this PR is already too long)

2023-08-23 09:06 UTC, malparty commented on lib/api/v1/controllers/auth_test.go
> +			It("returns an unprocessable entity status", func() {
```suggestion
			It("returns the unprocessable entity status", func() {
```

As a quick rule of thumb:
- use "a / an" when refering to an unknown item
  e.g. 1: there are many chair. I need to seat on a chair (here `a` means `any chair will do`, we don't care of the identity of the chair)
  e.g. 2: there are many chaer. I need to seat on the blue chair (here `the` means `their is only 1 bule chair, I can identity it)

As there is only 1 unprocessable entity status (422), we return `the` status.
In the case there would be multiple statuses, we would use `a`. For example "it returns a 40{X} status" (meaning any of the 400, 401, 402, 403, ... statuses).

2023-08-23 09:11 UTC, markgravity commented on helpers/json/response_json.go
> +func RenderError(ctx *gin.Context, statusCode int, errMessage string, errorCode string) {
@malparty Please ignore it as it's the code base of gulf project, we will use it later 🙏

2023-08-23 09:11 UTC, markgravity commented on helpers/json/response_json.go
> +func RenderErrorWithMeta(ctx *gin.Context, statusCode int, errMessage string, errorCode string, meta *map[string]interface{}) {
@malparty same here too 🙏

2023-08-23 09:12 UTC, markgravity commented on helpers/json/response_json.go
> +func RenderJSONWithMeta(ctx *gin.Context, code int, data interface{}, meta *jsonapi.Meta) {
It's will be used with list keyword API 🙏

2023-08-24 03:03 UTC, malparty approved these changes
💡  Don't hesitate to add insight in the PR description if some dead code is added for future purposes as it's hard to review a helper function if it is not used at all (because we miss the whole context of why we need it). 🙇

2023-08-25 02:55 UTC, markgravity commented
> 💡 Don't hesitate to add insight in the PR description if some dead code is added for future purposes as it's hard to review a helper function if it is not used at all (because we miss the whole context of why we need it). 🙇

Got it @malparty , I will take care of it on the next PRs 👍

2023-08-25 02:59 UTC, merged