[#48] [Backend] As a user, I will be required a valid token when sending authenticated request
markgravity/golang-ic pull request #51
Opened 2023-09-05 06:56 UTC by markgravity

- Close #48 

## What happened 👀

- Add authenticated request middleware
- Apply the above middleware for POST `keywords/upload`

## Insight 📝

n/a

## Proof Of Work 📹

![CleanShot 2023-09-05 at 13 53 55](https://github.com/markgravity/golang-ic/assets/17875522/905bc0f8-4f6b-48ea-95f7-e1681275066c)

2023-09-25 03:22 UTC, suho commented on lib/api/v1/controllers/keywords_test.go
> +				headers.Set("Authorization", "Bearer "+helpers.GenerateToken(user.Base.ID.String()))
I think we can do this
```suggestion
				headers := http.Header{
					"Authorization": {"Bearer "+helpers.GenerateToken(user.Base.ID.String())} }
```

2023-09-25 03:22 UTC, suho commented on lib/api/v1/controllers/keywords_test.go
> +				headers.Set("Authorization", "Bearer "+helpers.GenerateToken(user.Base.ID.String()))
If you agree with this, please update for other test cases

2023-09-25 07:20 UTC, malparty requested changes

2023-09-25 07:20 UTC, malparty commented on lib/api/v1/controllers/keywords_test.go
> +				middlewares.HandleAuthenticatedRequest()(ctx)
Should we define the needed helpers directly? So we won't duplycate this code in every tests?

For example: in https://github.com/nimblehq/varun-api/blob/develop/lib/api/v1/controllers/jobs_test.go#L48

```
						pilot := FabricatePilot(test.ThaiPhoneNumber())
						farmer := FabricateFarmer(test.ThaiPhoneNumber())
						now := time.Now()
						_ = FabricateJobFor(farmer, pilot, &now, "all-day", models.AcceptedStatus)

						ctx, resp := test.MakeAuthenticatedRequest(http.MethodGet, "/jobs", nil, pilot)
						jobsController := controllers.JobsController{}

						jobsController.Index(ctx)

						Expect(resp.Code).To(Equal(http.StatusOK))
```

Only 1 line is needed in the tests, so it's easiers to write and read :)

2023-09-25 07:20 UTC, malparty commented on lib/middlewares/authenticated_request.go
Should we rename it `authentication`? Because this middleware does not handle the authenticated requests, it handles the authentication before the authenticated requests can be handled 🦄

2023-09-25 07:20 UTC, malparty commented on lib/middlewares/authenticated_request_test.go
> +			It("sets data to context", func() {
Should we be more precise about what data? This test description does not help understand the code. 

```suggestion
			It("sets the 'user' key with the current user id, into the context", func() {
```

2023-10-02 08:40 UTC, malparty approved these changes

2023-10-06 08:39 UTC, suho approved these changes

2023-10-06 08:39 UTC, suho approved these changes

2023-10-09 06:24 UTC, merged