[#8] Add GET /keywords API
markgravity/golang-ic pull request #53
Opened 2023-10-02 03:51 UTC by markgravity

- Close #8

## What happened 👀

- Add `GET /keywords` API
- Update tests

## Insight 📝

n/a

## Proof Of Work 📹

![CleanShot 2023-10-02 at 10 50 08](https://github.com/markgravity/golang-ic/assets/17875522/abd5e01e-4741-448d-8599-35f7ef9c17a9)

2023-10-02 09:14 UTC, malparty requested changes

2023-10-02 09:14 UTC, malparty commented on lib/api/v1/controllers/keywords.go
> +func (KeywordsController) List(ctx *gin.Context) {
```suggestion
func (KeywordsController) Index(ctx *gin.Context) {
```

There is a sort of [CRUD convention](https://medium.com/@atharvakulkarniamk/restful-routing-mapping-rest-to-crud-dbb2f32f748c), there is no obligation to follow it, but as most teammates (and web frameworks) know and apply it, it's more effective to describe what it actually does 👍

2023-10-02 09:14 UTC, malparty commented on lib/api/v1/controllers/keywords.go
> +	user := value.(models.User)
Should we move that into the Base controller so that we can directly refer to `current_user` in any action? 🤔 

See https://github.com/nimblehq/varun-api/blob/develop/lib/api/v1/controllers/base.go

Can be used easily as:
```
func (c *KeywordsController) List(ctx *gin.Context) {
  currentUser := c.GetCurrentUser(ctx)
```

2023-10-02 09:14 UTC, malparty commented on lib/api/v1/controllers/keywords_test.go
> +			It("returns correct response body", func() {
```suggestion
			It("returns the keywords that belong to the current user, serialized in JSON", func() {
```

Any action returns the correct response body, therefore this description does not add value (and if so, we could just remove it... or improve it so value is provided for the readers).

2023-10-02 09:14 UTC, malparty commented on lib/api/v1/routers/router.go
> +	authenticatedV1.GET("/keywords", controllers.KeywordsController{}.List)
```suggestion
	authenticatedV1.GET("/keywords", controllers.KeywordsController{}.List)
	authenticatedV1.POST("/keywords/upload", controllers.KeywordsController{}.Upload)
```

We can order it by route name (the root `keywords` before any sub-route). Or by CRUD conventions wich order follows the table:

![image](https://github.com/markgravity/golang-ic/assets/77609814/64cfbeb9-2fcf-415b-8840-f72b347ba16a)

2023-10-02 09:14 UTC, malparty commented on lib/models/response/keyword.go
> +package responsemodels
I'm not sure about the file name and package name 🤔 

My recommendation would be:
- file: `lib/models/responses/keyword.go`
- package: `modelsresponses` (just concat both folder names)

But you might want to explore other code bases or web resources to confirm that 🤔 
(and if you already did, please share them, I'd be happy to learn too ^^)

2023-10-02 09:14 UTC, malparty commented on test/api/schemas/response/keyword/success.json
> +              "type": "string"
```suggestion
              "type": "string",
              "format": "uuid"
```

Does it work with UUID here? According to [json-schema](https://json-schema.org/draft/2020-12/json-schema-validation#section-7.3.5-2.10) we could validate this format instead of allowing any random string 👍

2023-10-02 09:14 UTC, malparty commented on test/api/schemas/response/keyword/success.json
> +                  "type": "string"
```suggestion
                  "type": "string",
                  "enum": ["processing", "failed", "succeed"]
```

The good point is that you can also remove the status you do NOT expect in the `index` action (maybe we don't want to return the keywords that are `processing`).
it's an additional way to test 👍

2023-10-04 02:59 UTC, markgravity commented on lib/models/response/keyword.go
> +package responsemodels
Agree with this convention 👍

2023-10-04 03:07 UTC, markgravity commented
@malparty resolved your comments 🙏

2023-10-06 06:17 UTC, malparty commented on test/api/schemas/response/keyword/success.json
> +                  "type": "string"
I think you made the changes in 1 out of 2 of the objects... You can see the lines referred by the 2 comments are unchanged (but it's implemented later in the file ^^)

2023-10-06 06:18 UTC, malparty approved these changes
Approved ahead with a last comment.

Looks great now 🚀

2023-10-06 06:28 UTC, markgravity commented on test/api/schemas/response/keyword/success.json
> +                  "type": "string"
Nice catch, fixed it 🙏

2023-10-06 08:46 UTC, suho approved these changes
Just small improvements, so I will give you pre-approving

2023-10-06 08:46 UTC, suho commented on lib/api/v1/controllers/base_test.go
> +	. "github.com/onsi/gomega"
```suggestion
	"net/http"

	"github.com/markgravity/golang-ic/test/fabricators"
	"github.com/markgravity/golang-ic/lib/api/v1/controllers"
	"github.com/markgravity/golang-ic/test"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
```

2023-10-06 08:46 UTC, suho commented on test/api/schemas/response/keyword/success.json
> +}
Please add new line at the end of this file

2023-10-09 06:27 UTC, merged